spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 8837
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  mail:
    host: ${settings.mail.host}
    port: ${settings.mail.port}
    username: ${settings.mail.username}
    password: ${settings.mail.password}
  sql:
    init:
      platform: postgres
      mode: always
      schema-locations: classpath:schema-prod.sql
