spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:schema-dev.sql
      data-locations: classpath:data-dev.sql
