DROP TABLE IF EXISTS answer_selected_option_assoc;
DROP TABLE IF EXISTS answer;
DROP TABLE IF EXISTS submission;
DROP TABLE IF EXISTS option;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS "user";

CREATE TABLE question
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label       TEXT        NOT NULL,
    text        TEXT,
    type        VARCHAR(20) NOT NULL,
    is_required BOOLEAN     NOT NULL,
    is_active   BOOLEAN     NOT NULL
);

CREATE TABLE option
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    index       INT,
    text        TEXT NOT NULL,
    question_id INT,
    CONSTRAINT fk_question FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE
);

CREATE TABLE submission
(
    id   INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    submission_time TIMESTAMP NOT NULL
);

CREATE TABLE answer
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text          TEXT,
    submission_id INT REFERENCES submission (id) ON DELETE CASCADE,
    question_id   INT REFERENCES question (id) ON DELETE CASCADE
);


CREATE TABLE answer_selected_option_assoc
(
    answer_id INT REFERENCES answer (id),
    option_id INT REFERENCES option (id),
    CONSTRAINT pk_answer_option PRIMARY KEY (answer_id, option_id)
);

CREATE TABLE "user" (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    role TEXT NOT NULL
);